# Generated by Django 2.2 on 2021-08-31 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_auto_20210830_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='prodt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.products'),
        ),
    ]
